# Generated by Django 4.2.10 on 2024-02-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_desc_estados_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
    ]
