# Generated by Django 4.2.10 on 2024-02-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_usuarios_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='documento',
        ),
    ]
