# Generated by Django 4.2.10 on 2024-03-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
