# Generated by Django 4.2.10 on 2024-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_clientes_documento_clientes_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productospedido',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='productospedido',
            old_name='id_producto',
            new_name='producto',
        ),
    ]
