# Generated by Django 4.2.10 on 2024-03-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_handlerdespacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlerdespacho',
            old_name='vendedor',
            new_name='despachador',
        ),
    ]
