# Generated by Django 4.2.10 on 2024-03-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pedidosactivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosactivos',
            old_name='producto',
            new_name='pedido',
        ),
    ]
