# Generated by Django 4.2.10 on 2024-03-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_producto_pedidosactivos_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosactivos',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pedido'),
        ),
    ]
