# Generated by Django 4.2.10 on 2024-03-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_pedidosactivos_repartosactivos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='repartido_hora',
        ),
    ]
