# Generated by Django 4.2.10 on 2024-03-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_pedido_completado_hora_pedido_completado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='despachado_por',
        ),
    ]
