# Generated by Django 4.2.10 on 2024-04-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_pedido_despachado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlerdespacho',
            old_name='despachador',
            new_name='empacador',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='asignador_reparto',
            new_name='despachador_reparto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='asignacion_hora',
            new_name='despacho_hora',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='despachado_hora',
            new_name='empacado_hora',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='notaDespachador',
            new_name='notaEmpacador',
        ),
    ]
