# Generated by Django 4.2.10 on 2024-04-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_despachador_handlerdespacho_empacador_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HandlerDespacho',
            new_name='HandlerEmpaquetacion',
        ),
    ]
