# Generated by Django 4.2.10 on 2024-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_pedido_repartido_por_handlerreparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='despacho_modificado_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
