# Generated by Django 4.2.10 on 2024-04-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_pedido_despacho_modificado_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolReparto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='handlerreparto',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rolreparto'),
        ),
    ]
