# Generated by Django 4.2.10 on 2024-04-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pedido_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='consecutivo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
