# Generated by Django 4.2.10 on 2024-04-05 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_pedido_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='credito_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='credito_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
