# Generated by Django 4.2.10 on 2024-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_productospedido_tipo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsecutivo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25)),
            ],
        ),
    ]
