# Generated by Django 4.2.10 on 2024-06-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_tipoconsecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_consecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipoconsecutivo'),
        ),
    ]
