# Generated by Django 4.2.10 on 2024-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_pedido_tipo_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productospedido',
            name='paquete',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productospedido',
            name='peso',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
