# Generated by Django 4.2.10 on 2024-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_productospedido_paquete_productospedido_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='check_bodega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
