# Generated by Django 4.2.10 on 2024-06-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_pedido_checkeado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='valor',
        ),
    ]
