# Generated by Django 4.2.10 on 2024-06-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_pedido_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='dinero_generado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
