# Generated by Django 4.2.10 on 2024-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_clientes_dinero_generado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productospedido',
            name='paquete',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipoconsecutivo',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
