# Generated by Django 4.2.10 on 2024-07-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_pedido_consecutivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='completado_hora',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='completado_por',
        ),
    ]
