# Generated by Django 4.2.10 on 2024-07-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_pedido_consecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='check_factura_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_factura_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
