-- Tipos de usuarios
insert into main_tipousuario (id, description) values(0, 'Gerente');
insert into main_tipousuario (id, description) values(1, 'Administrador');
insert into main_tipousuario (id, description) values(2, 'Vendedor');
insert into main_tipousuario (id, description) values(3, 'Despachador');
insert into main_tipousuario (id, description) values(4, 'Repartidor');
--select * from main_tipousuario